export const cards = [
    {
        id: 1,
        title: "AI Artists",
        desc: "Add talent to AI",
        img: "../public/img/slider_img/coffe.jpeg",
    },
    {
        id: 2,
        title: "Logo Design",
        desc: "Build yor brand",
        img: "../public/img/slider_img/coffe_2.jpeg",
    },
    {
        id: 3,
        title: "WordPress",
        desc: "Customize your site",
        img: "../public/img/slider_img/bread.jpeg",
    },
    {
        id: 4,
        title: "Voice Over",
        desc: "Share your message",
        img: "../public/img/slider_img/bathroom_items.jpeg",
    },
    {
        id: 5,
        title: "Video Explainer",
        desc: "Engage your audience",
        img: "../public/img/slider_img/bathroom.jpeg",
    },
    {
        id: 6,
        title: "Social Media",
        desc: "Reach more customers",
        img: "../public/img/slider_img/camera.jpeg",
    },
    {
        id: 7,
        title: "SEO",
        desc: "Unlock growth online",
        img: "../public/img/slider_img/hands.jpeg",
    },
    {
        id: 8,
        title: "Illustration",
        desc: "Color you dreams",
        img: "../public/img/slider_img/painting.jpeg",
    },
];

export const projects = [
    {
        id: 1,
        img: "../public/img/1462935.jpeg",
        pp: "../public/img/774909.webp",
        cat: "Web and Mobile Design",
        username: "Anna Bell",
    },
    {
        id: 2,
        img: "../public/img/270408.webp",
        pp: "../public/img/91227.webp",
        cat: "Logo Design",
        username: "Morton Green",
    },
    {
        id: 3,
        img: "../public/img/4144923.webp",
        pp: "../public/img/1181686.jpeg",
        cat: "Animated GIFs",
        username: "Emmett Potter",
    },
    {
        id: 4,
        img: "../public/img/4348404.jpeg",
        pp: "../public/img/2182970.webp",
        cat: "Packaging Design",
        username: "Freddie Johnston",
    },
    {
        id: 5,
        img: "../public/img/4458554.jpeg",
        pp: "../public/img/733872.webp",
        cat: "Social Media Design",
        username: "Audrey Richards",
    },
    {
        id: 6,
        img: "../public/img/4465831.webp",
        pp: "../public/img/1036627.webp",
        cat: "Illustration",
        username: "Dalton Hudson",
    },
    {
        id: 7,
        img: "../public/img/6077368.webp",
        pp: "../public/img/1858175.webp",
        cat: "Book Design",
        username: "Hannah Dougherty",
    },
    {
        id: 8,
        img: "../public/img/4065876.webp",
        pp: "../public/img/1680175.jpeg",
        cat: "Digital Marketing",
        username: "Ward Brewer",
    },
];

export const gigs = [
    {
        id: 1,
        img: "../public/img/pexels-photo-580151.jpeg",
        pp: "../public/img/pexels-photo-720598.webp",
        desc: "I will create ai art character from your images and prompts",
        price: 59,
        star: 5,
        username: "Anna Bell",
    },
    {
        id: 2,
        img: "../public/img/pexels-photo-4145190.jpeg",
        pp: "../public/img/pexels-photo-1036627.webp",
        desc: "I will create ultra high quality character art with ai",
        price: 79,
        star: 5,
        username: "Lannie Coleman",
    },
    {
        id: 3,
        img: "../public/img/pexels-photo-8797307.jpeg",
        pp: "../public/img/pexels-photo-1062280.webp",
        desc: "I will creating unique ai generated artworks mid journey ai artist",
        price: 112,
        star: 5,
        username: "Carol Steve",
    },
    {
        id: 4,
        img: "../public/img/pexels-photo-5708069.webp",
        pp: "../public/img/pexels-photo-1681010.jpeg",
        desc: "I will create custom ai generated artwork using your photos",
        price: 99,
        star: 4,
        username: "Don Weber",
    },
    {
        id: 5,
        img: "../public/img/pexels-photo-5699456.webp",
        pp: "../public/img/pexels-photo-1771383.webp",
        desc: "I will recreate your dreams in high quality pictures",
        price: 59,
        star: 5,
        username: "Audrey Richards",
    },
    {
        id: 6,
        img: "../public/img/pexels-photo-8100784.jpeg",
        pp: "../public/img/pexels-photo-715546.jpeg",
        desc: "I will create ai digital art illustration hyper realistic painting",
        price: 79,
        star: 4,
        username: "Walton Shepard ",
    },
    {
        id: 7,
        img: "../public/img/pexels-photo-6039245.jpeg",
        pp: "../public/img/pexels-photo-720606.webp",
        desc: "I will generate images with your prompts using ai dalle",
        price: 89,
        star: 5,
        username: "Waverly Schaefer",
    },
    {
        id: 8,
        img: "../public/img/pexels-photo-5490778.webp",
        pp: "../public/img/pexels-photo-1699159.jpeg",
        desc: "I will create custom art using midjourney generator",
        price: 110,
        star: 4,
        username: "Wilton Hunt",
    },
];
